name: confeitapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  drift: ^2.26.0
  path_provider: ^2.1.5
  geocoding: ^2.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  mocktail: 1.0.4
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.15.0

flutter:
  uses-material-design: true
